web_ui/web_app/app/__init__.py
from flask import Flask, render_template
import os
import sys
from app.home import home as home_blueprint
from turbo_flask import Turbo
from app.turbo_wrapper.turbo_wrapper import turboWrapper
from app.db.database_instance import db_instance

app_instance= None

def init_extensions(app: Flask):
    
    # use .init_app() on your extensions to register them on
    # the Flask instance
    turboWrapper.turbo= Turbo(app)
    



def get_root_dir_abs_path() -> str:
    """
    Get the absolute path to the root directory of the application.
    """
    # Check if the application runs in a bundled executable from PyInstaller.
    # When executed, the bundled executable get's unpacked into the temporary directory sys._MEIPASS.
    # See also: https://pyinstaller.readthedocs.io/en/stable/runtime-information.html#using-file
    return getattr(sys, "_MEIPASS", os.path.abspath(os.path.dirname(__file__)))

def create_app(config_object_name,db_uri) -> Flask:
    """
    :param config_object_name: The python path of the config object.
                               E.g. appname.settings.ProdConf
    :param db_uri: path to database path 
    """

    root_dir_abs_path = get_root_dir_abs_path()

    print(root_dir_abs_path)
    # Initialize the core application
    global app_instance
    
    app_instance = Flask(
        __name__,
        instance_relative_config=False,
        static_folder=os.path.join(root_dir_abs_path, "static"),
        template_folder=os.path.join(root_dir_abs_path, "templates"),
    )
    app_instance.config.from_object(config_object_name)

    print(f"Db_uri database {db_uri}")
    
    app_instance.config['SQLALCHEMY_DATABASE_URI'] = db_uri
    app_instance.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
    
    
    db_instance.db.init_app(app_instance)

    # Initialize Plugins at startup using init_app()
    init_extensions(app_instance)

    with app_instance.app_context():
        # Register Blueprints
        app_instance.register_blueprint(home_blueprint, url_prefix="/")
        
        db_instance.db.create_all()
        
        @app_instance.errorhandler(404)
        def page_not_found(error):
            return render_template("page/errors/404.html", title="Page Not Found"), 404

        return app_instance

web_ui/web_app/app/home/__init__.py
from flask import Blueprint
from app.data.data import Data


data_instance= Data()

print(f"app_name {__name__}")
home = Blueprint("home", __name__)


from . import views

web_ui/web_app/app/home/views.py
from flask import flash, render_template, request, jsonify, Response, make_response, session, current_app, redirect, url_for, send_file
import zipfile
import os


from . import home

from app.db.mlflow_shema import Configuration
from app.db.database_instance import db_instance


# Views Import
import app.home.views_dataset
import app.home.views_training
import app.home.views_optimization
import app.home.views_deploy

import json
from pathlib import Path


from app.home.utils import generate_ssh_configuration
from app.conf.conf_handler import configurationHandler
from sqlalchemy.exc import IntegrityError
import random
# Dove sono arrivato
"""
Ho creato la pagina di visualizzazione delle statistiche in una tabella. Il primo problema è che le metriche visualizzate,
si riferiscono sempre all'ultima epoca quindi è difficile eseguire un confronto tra i modelli per capire quale modello performa meglio.
(magari ultima epoca non è la migliore)

Si potrebbe creare una tabella dinamica in cui l'utente seleziona la metrica con cui eseguire i confronti dei modelli e in base alla 
stessa versione del dataset o altro che posso specificare vedere quale modello è il migliore.

Adesso da interfaccia grafica è possibile eseguire il training e i dati sono aggiornati a database che possono essere visualizzati nella
pagina

Durante il training non ho nessun tipo di feedback
Per ogni nome di esperimento è creato un database apposito. In base al valore experiment_name: testWindows nella gui_cfg.yaml
Forse dovrei creare una lista di esperimenti e quando uno clicca l'esperimento si setta il training


"""


@home.route('/download_folder/')
def download_folder():

    # model_path=request.args.get('model_path')
    data = request.args.get('onnx_json_data')

    print("DATA")
    print(data)

    excluded_extensions = ['.zip']

    configuration_path = json.loads(data)["onnx_cfg"] + "/"

    download_name = "download"
    download_folder = configuration_path + "download/"

    # create download folder if not exists
    Path(download_folder).mkdir(
        parents=True, exist_ok=True)

    onnx_model_path = json.loads(data)["model_path"] + "onnx/"

    zip_path = download_folder + download_name + '.zip'
    configuration_path

    # folder_path= "C:/Users/erict/OneDrive/Desktop/Develop/ai4prodGuiData/Experiment/classification/test_intel/exp_6/test/dataset_version_2/"

    with zipfile.ZipFile(zip_path, 'w') as zipf:
        for root, _, files in os.walk(configuration_path):
            for file in files:
                file_path = os.path.join(root, file)
                if excluded_extensions is None or not file_path.endswith(tuple(excluded_extensions)):
                    arcname = os.path.relpath(file_path, configuration_path)
                    zipf.write(file_path, arcname=arcname)
        for root, _, files in os.walk(onnx_model_path):
            for file in files:
                file_path = os.path.join(root, file)
                if excluded_extensions is None or not file_path.endswith(tuple(excluded_extensions)):
                    arcname = os.path.relpath(file_path, onnx_model_path)
                    zipf.write(file_path, arcname=arcname)

    # Send the zip file as a download response
    return send_file(zip_path, as_attachment=True, download_name=f"{download_name}.zip")


@home.route('/configuration/generat_ssh_key/', methods=['POST'])
def get_data():
    data = request.get_json()

    email = data["email"]
    print(email)
    ssh_key = generate_ssh_configuration(email)
    ssh_key = {"ssh_key": ssh_key}
    return jsonify(ssh_key)


@home.route('/configuration', methods=["GET", "POST"])
def configuration():

   

    if request.method == "POST":
        print("Form submission")
        configuration_name = request.form['configuration_name']
        # TODO: At current time user email is not saved to database
        bitbucket_email = ""
        base_path_experiment = request.form['base_path_experiment']
        task = request.form.get('task')
        bitbucket_workspace = request.form['bitbucket_workspace']
        bitbucket_username = request.form['bitbucket_username']
        bitbucket_password = request.form['bitbucket_password']
        dvc_remote_ssh_user = request.form['dvc_remote_ssh_user']
        dvc_remote_ssh_psw = request.form['dvc_remote_ssh_psw']
        dvc_remote_ssh_ip = request.form['dvc_remote_ssh_ip']
        dvc_remote_path = request.form['dvc_remote_path']

        if (request.form['base_path_experiment'] == ""):
            base_path_experiment = configurationHandler.base_path_experiment
        
        conf = Configuration(
            configuration_name=configuration_name,
            bitbucket_email=bitbucket_email,
            base_path_experiment=base_path_experiment,
            task=task,
            bitbucket_username=bitbucket_username,
            bitbucket_password=bitbucket_password,
            bitbucket_workspace=bitbucket_workspace,
            dvc_remote_ssh_user=dvc_remote_ssh_user,
            dvc_remote_ssh_psw=dvc_remote_ssh_psw,
            dvc_remote_ssh_ip=dvc_remote_ssh_ip,
            dvc_remote_path=dvc_remote_path,
        )

        db_instance.db.session.add(conf)
        db_instance.db.session.commit()
        flash('Configurazione creata con successo', 'success')
        return redirect(url_for('home.configuration'))
        # except IntegrityError as e:
        #     print("INTEGRITY")
        #     # Rollback the transaction to prevent data corruption
        #     db_instance.db.session.rollback()
        #     flash('Nome configurazione già presente', 'error')
        #     return redirect(url_for('home.configuration'))

        # except Exception as e:
        #     error_message = "Errore generico.Riprova"

    return render_template('page/home/configuration.html')

web_ui/web_app/app/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>{{ title }} | Electron App</title>
    <!-- App style -->
    <link
      href="{{ url_for('static', filename='css/style.css') }}"
      rel="stylesheet"
    />

    <link rel="stylesheet" href="/static/bootstrap/css/bootstrap.min.css" />
    <link rel="stylesheet" href="/static/jquery-ui/jquery-ui.min.css" />

    <script src="/static/jquery/js/jquery-3.6.0.min.js"></script>
    <link href="/static/jquery/css/roundslider.css" rel="stylesheet" />
    <script src="/static/jquery/js/roundslider.js"></script>
    <script src="/static/bootstrap/js/bootstrap.min.js"></script>
    <script src="/static/jquery-ui/jquery-ui.min.js"></script>
    <script src="/static/jquery-ui-touch-punch/jquery.ui.touch-punch.min.js"></script>
    <script src="/static/plotly/cdn.plot.ly_plotly-latest.min.js"></script>
    {{ turbo() }}
  </head>

  <body>
    {% block body %} {% endblock %}
  </body>
</html>

web_ui/web_app/app/templates/page/component/nav_bar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="/">Logo</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('home.dataset') }}">Dataset</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('home.training') }}">Training</a>
            </li>
            <li class="nav-item">
                <a class="nav-link"href="{{ url_for('home.optimization') }}">Ottimizzazione</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('home.configuration') }}">Configuration</a>
            </li>
        </ul>
    </div>
</nav>

web_ui/web_app/app/templates/page/home/configuration.html
{% extends "base.html" %} {% block title %}Home{% endblock %} {% block body %}

<div class="containerd-flex flex-column">
  {% include "page/component/nav_bar.html" %}

  <div></div>
  <div class="container mt-4">
    <div class="row">

      <div class="col"></div>
      <div class="col-6">
        <h2>Configurazione Generale</h2>

        {% with errors = get_flashed_messages(category_filter=["error"]) %}
        {% if errors %}
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
          <ul>
            {%- for msg in errors %}
            <li>{{ msg }}</li>
            {% endfor -%}
          </ul>

          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        {% endif %}
        {% endwith %}

        {% with messages = get_flashed_messages(category_filter=["success"]) %}
        {% if messages %}
        <div class="alert alert-success alert-dismissible fade show" role="alert">
          <ul>
            {%- for msg in messages %}
            <li>{{ msg }}</li>
            {% endfor -%}
          </ul>

          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        {% endif %}
        {% endwith %}


        <div class="form-group">
          <label for="bitbucket_email">Bitbucket email:</label>
          <input type="text" class="form-control" placeholder="email usata per connettersi account bitbucket"
            name="bitbucket_email" id="bitbucket_email">
        </div>

        <div class="form-group text-center">
          <label for="bitbucket_workspace">Genera la chiave di Bitbucket</label>
          <p><b>Utilizza questo link</b> per capire come settare la chiave su bitbucket <a
              href="https://support.atlassian.com/bitbucket-cloud/docs/set-up-personal-ssh-keys-on-linux/">Clicca
              qui</a></p>
          <ol>
            <li> Cliica su Genera </li>
            <li> Copia la chiave su bitbucket come specificato nel link nella sezione "Provide Bitbucket Cloud with
              your public key" </li>
          </ol>
          <textarea id="ssh_key" rows="10" cols="50"></textarea>
          <button type="button" id="ssh_generator" class="btn btn-danger">Genera</button>
        </div>

        <h2>Configurazione di Training</h2>

        <h6> Crea la configurazione che potrai usare per gestire i dati e il training</h6>
        <form action="{{url_for('home.configuration')}}" method="POST" class="mt-5" enctype="multipart/form-data">

          <div class="form-group">
            <label for="configuration_name">Nome Configurazione</label>
            <input type="text" class="form-control" placeholder="nome configurazione" name="configuration_name"
              id="configuration_name">
          </div>

          <div class="form-group">
            <label for="task">Select an option</label>
            <select class="form-control" id="task" name="task">
              <option value="anomaly_detection">anomaly detection</option>
              <option value="classification">classification</option>
              <option value="object_detection">object detection </option>
              <option value="segmentation">segmentation</option>
            </select>
          </div>

          <div class="form-group">
            <label for="bitbucket_username">Bitbucket Username:</label>
            <input type="text" class="form-control" placeholder="nome bitbucket_username" name="bitbucket_username"
              id="bitbucket_username">
          </div>
          <div class="form-group">
            <p> Segui questa guida per creare un app password per interagire con bitbucket<a
                href="https://support.atlassian.com/bitbucket-cloud/docs/create-an-app-password/">Crea app password</a>
            </p>
            <label for="bitbucket_password">Bitbucket App Password:</label>
            <input type="text" class="form-control" placeholder="nome workspace bitbucket" name="bitbucket_password"
              id="bitbucket_password">
          </div>
          <div class="form-group">
            <label for="bitbucket_workspace">Bitbucket Workspace:</label>
            <input type="text" class="form-control" placeholder="nome workspace bitbucket" name="bitbucket_workspace"
              id="bitbucket_workspace">
          </div>

          <div class="form-group">
            <label for="base_path_experiment">Experiment Path:</label>
            <input type="text" placeholder="Lascia vuoto per usare la configurazione di default " class="form-control"
              name="base_path_experiment" id="base_path_experiment">
          </div>
          <div class="form-group">
            <label for="dvc_remote_path">Dvc Remote Path:</label>
            <input type="text" class="form-control" placeholder="cambia soloe se imposti i dataset su un host remoto"
              name="dvc_remote_path" id="dvc_remote_path">
          </div>

          <div class="form-group">
            <label for="dvc_remote_ssh_user">Remote ssh User:</label>
            <input type="text" class="form-control" placeholder="utente ssh per salvare i dataset su host remoto"
              name="dvc_remote_ssh_user" id="dvc_remote_ssh_user">
          </div>
          <div class="form-group">
            <label for="dvc_remote_ssh_psw">Remote ssh Password:</label>
            <input type="password" class="form-control" placeholder="password connessione ssh remota"
              name="dvc_remote_ssh_psw" id="dvc_remote_ssh_psw">
          </div>
          <div class="form-group">
            <label for="dvc_remote_ssh_ip">Remote ssh IP:</label>
            <input type="text" placeholder="Ip server remoto" class="form-control" name="dvc_remote_ssh_ip"
              id="dvc_remote_ssh_ip">
          </div>
          <button type="submit" class="btn btn-primary">Crea Configurazione</button>

        </form>
      </div>
      <div class="col"></div>
    </div>
  </div>


  <script>
    document.getElementById('ssh_generator').addEventListener('click', function () {
      const data = document.getElementById('bitbucket_email').value;
      fetch('/configuration/generat_ssh_key/', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ email: data }),
      })
        .then(response => response.json())
        .then(data => {
          console.log(data);
          document.getElementById('ssh_key').innerText = data.ssh_key;
        })
        .catch(error => {
          console.error('Error:', error);
        });
    });
  </script>

  <!-- https://stackoverflow.com/a/30011819 -->
  <script type="text/javascript" src="{{url_for('static', filename='js/index.js')}}"></script>
</div>

{% endblock %}

web_ui/web_app/app/templates/page/home/dataset.html
{% extends "base.html" %} {% block title %}Home{% endblock %} {% block body %}

<div class="containerd-flex flex-column">

    {% include "page/component/nav_bar.html" %}


    <div class="container">
        <div class="row">
            <div class="col"></div>
            <div class="col-6">
                <h2>Create Dataset Configuration</h2>
            </div>
            <div class="col"></div>

        </div>
        <div class="row">

            <div class="col"></div>
            <div class="col-6">
                <form action="{{url_for('home.dataset')}}" method="POST" enctype="multipart/form-data">
                    
                    <div class="form-group">
                        <label for="repo_name">Repository Name</label>
                        <input type="text" class="form-control" name="repo_name" id="repo_name">
                    </div>
                    <div class="form-group">
                        <label for="configuration_list">Select an option</label>
                        <select class="form-control" id="configuration_list" name="configuration_list">
                            {% for configuration in configurations_list %}
                            <option value="{{configuration.id}}">{{configuration.configuration_name}}</option>
                            {% endfor %}
                        </select>
                      </div>


                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
            <div class="col"></div>
        </div>
        <div class="row">
            <table class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th class="text-center">Path Locale/th>
                        <th class="text-center">Path Remota</th>
                        <th class="text-center">Versione Corrente</th>
                        <th class="text-center">Statistiche</th>
                        <th class="text-center">Stato</th>
                    </tr>
                </thead>
                <tbody>
                    {% for dataset in datasets_list %}
                    <tr>
                        {% if dataset.is_selected==1 %} 
                        <tr class="table-success">
                            <td onclick="expandCell(this)" class="text-center truncate-custom">{{ dataset.local_path }}</td>
                            <td onclick="expandCell(this)" class="text-center truncate-custom">{{ dataset.git_remote_path }}</td>
                            <td onclick="expandCell(this)" class="text-center truncate-custom">{{dataset.current_version}}</td>
                            <td onclick="expandCell(this)" class="text-center truncate-custom"><a class="btn btn-success" href="{{ url_for('home.dataset_statistics', dataset_id=dataset.id) }}">Go</a></td>
                        
                            <td class="text-center"> <b>Selezionata</b> </td>
                        </tr>

                        {% else %}

                        <tr>
                              
                        <td onclick="expandCell(this)" class="text-center truncate-custom">{{ dataset.local_path }}</td>
                        <td onclick="expandCell(this)" class="text-center truncate-custom">{{ dataset.git_remote_path }}</td>
                        <td onclick="expandCell(this)" class="text-center truncate-custom">{{dataset.current_version}}</td>
                        <td onclick="expandCell(this)" class="text-center truncate-custom"><a class="btn btn-success" href="{{ url_for('home.dataset_statistics', dataset_id=dataset.id) }}">Go</a></td>
                        <td class="text-center"><a class="btn btn-primary" href="{{ url_for('home.change_main_dataset', dataset_id= dataset.id) }}">Cambia</a>
                    </tr>
                        {% endif %}
                      
                    </tr>
                    {% endfor %}
                    
                </tbody>
            </table>
        </div>
    </div>

</div>

<script>
    function expandCell(cell) {
        cell.classList.toggle("expanded");
    }
</script>
{% endblock %}

web_ui/web_app/app/templates/page/home/dataset_statistics.html
{% extends "base.html" %} {% block title %}Home{% endblock %} {% block body %}

<div class="containerd-flex flex-column">
    {% include "page/component/nav_bar.html" %}

    <div class="container">

        <div class="row">
            <div class="col-6">
                <h2>Versions List </h2>

                <table class="table table-bordered table-striped">

                    <thead>
                        <tr>
                            <th class="text-center">Version</th>
                            <th class="text-center">Date</th>
                            <th class="text-center">Change Version</th>
                           
                        </tr>
                    </thead>
                    <tbody>

                        {% for dataset_version in datasets_versions_list %}
                        
                        {% if current_version==dataset_version.tag_version %} 
                        <tr class="table-success">
                            <td class="text-center"> <b>{{dataset_version.tag_version}}</b></td>
                            <td class="text-center" ><b>{{dataset_version.timestamp}}</b></td>
                            <td class="text-center"> <b>Selezionata</b> </td>
                        </tr>

                        {% else %}

                        <tr>
                            <td class="text-center">{{dataset_version.tag_version}}</td>
                            <td class="text-center" >{{dataset_version.timestamp}}</td>
                            <td class="text-center"><a class="btn btn-primary" href="{{ url_for('home.change_dataset_version', dataset_id= dataset_id,tag_version=dataset_version.tag_version) }}">Cambia</a>
                            </td>
                        </tr>
                        {% endif %}
                        {% endfor %}
                    </tbody>
                </table>
            </div>

          

            <div class="col-6 text-center">
                {% include "page/turbo_component/dataset_change.html" %}
            </div>

        </div>
    </div>

</div>
{% endblock %}

web_ui/web_app/app/templates/page/home/deploy.html
{% extends "base.html" %} {% block title %}Home{% endblock %} {% block body %}

<div class="containerd-flex flex-column">
  {% include "page/component/nav_bar.html" %}


  <div class="container mt-4">
    <h1>Deploy</h1>
    <p>Create Model and Configuration ready to be used in C++</p>

    <a  class="btn btn-success" href="{{ url_for('home.download_folder', onnx_json_data=onnx_json_data)}}"  id="download" style="visibility: hidden;">Download the model and configuration</a>
  
  </div>
</div>



<!-- https://stackoverflow.com/a/30011819 -->
<script>
  $(document).ready(function () {
    var intervalId;
    var timeoutCount = 0; // Number of times the interval has run
    var maxTimeoutCount = 10; // Maximum number of intervals
    // Define a function to recursively call the route
    function checkOnnx() {
      $.ajax({
        url: '/check_conversion/',
        method: 'GET',
        data: { "dataset_version": "{{dataset_version}}", "model_path": "{{model_path}}" },
        success: function (data) {
          if (data.message) {
            console.log("STOP INTERVAL");
            clearInterval(intervalId);
            $('#download').css('visibility', function(index, value) {
                return (value === 'hidden') ? 'visible' : 'hidden';
            });
          } else {
            //console.log("print message");
          }
        }
      });

      timeoutCount++;

      if (timeoutCount >= maxTimeoutCount) {
        console.log("Timeout Stop Interval")
        clearInterval(intervalId); // Stop the interval when the condition is met
      }
    }

    intervalId = setInterval(checkOnnx, 1000);

  });


</script>

</div>

{% endblock %}

web_ui/web_app/app/templates/page/home/optimization.html
{% extends "base.html" %} {% block title %}Home{% endblock %} {% block body %}

<div class="containerd-flex flex-column">
  {% include "page/component/nav_bar.html" %}

  <div class="container mt-4">
    <h1>About Us</h1>
    <p>This is the About page.</p>
  </div>

</div>



<!-- https://stackoverflow.com/a/30011819 -->
<script type="text/javascript" src="{{url_for('static', filename='js/index.js')}}"></script>
</div>

{% endblock %}

web_ui/web_app/app/templates/page/home/training.html
{% extends 'base.html' %} {% block title %}
Home
{% endblock %} {% block body %}
<div class="containerd-flex flex-column">
  {% include 'page/component/nav_bar.html' %}

  <div class="container mt-4">
    <h1>Configurazione di Training</h1>

    <div class="row">
      <table class="table table-bordered table-striped">
        <thead>
          <tr>
            <th class="text-center">Local Path</th>
            <th class="text-center">Remote Path</th>
            <th class="text-center">Current Version</th>
            <th class="text-center">Action</th>
          </tr>
        </thead>
        <tbody>

          <tr>
            <td onclick="expandCell(this)" class="text-center truncate-custom">{{ dataset.local_path }}</td>
            <td onclick="expandCell(this)" class="text-center truncate-custom">{{ dataset.git_remote_path }}</td>
            <td onclick="expandCell(this)" class="text-center truncate-custom">{{ dataset.current_version }}</td>
            <td onclick="expandCell(this)" class="text-center truncate-custom">
              <a class="btn btn-success" href="{{ url_for('home.dataset_statistics', dataset_id = dataset.id) }}">Go</a>
            </td>
          </tr>

        </tbody>
      </table>
    </div>

    <div class="row justify-content-center mt-4">
      <button class="btn btn-primary" id="startTraining">Start Training</button>
    </div>
    <div class="row justify-content-center mt-4">
      <div id="result"></div>
    </div>
    <div class="row justify-content-center mt-4">
      <a class="btn btn-info" href="{{ url_for('home.training_metrics', dataset_id=dataset_id) }}">Visualizza
        Metriche</a>
    </div>
  </div>

  <!-- https://stackoverflow.com/a/30011819 -->
  <!-- <script type="text/javascript" src="{{url_for('static', filename='js/index.js')}}"></script> -->
</div>

<script>
  $(document).ready(function () {
  
    const jsonData = {
      "dataset_id": "{{dataset_id}}",
  };

    $('#startTraining').click(function () {
      $.ajax({
        type: 'POST',
        contentType: 'application/json',
        data: JSON.stringify(jsonData),
        url: '/start_training',
        success: function (data) {
          $('#result').text(data.result)
        }
      })
    })
  })

  function expandCell(cell) {
    cell.classList.toggle('expanded')
  }
</script>
{% endblock %}

web_ui/web_app/app/templates/page/home/training_metrics.html
{% extends "base.html" %} {% block title %}Home{% endblock %} {% block body %}

<div class="containerd-flex flex-column">
  {% include "page/component/nav_bar.html" %}
  
  <div class="container mt-4">
    <div class="table-responsive">
    <table class="table table-bordered table-striped">
        <thead>
            <tr>
               
                {% for key in list_experiments_dict[0].keys() %}
                <th>{{ key }}</th>
                {% endfor %}
                <th> Action</th>
            </tr>
        </thead>
        <tbody>
            {% for item in list_experiments_dict %}
            <tr>
                {% for key, value in item.items() %}
                    <td onclick="expandCell(this)" class="truncate-custom">{{ value }}</td>
                {% endfor %}

               <td> <a class="btn btn-success" href="{{ url_for('home.deploy', experiment_number=item['experiment_number'],dataset_id=item["dataset_id"]) }}">Deploy</a></td>
            </tr>
          
        {% endfor %}
        </tbody>
    </table>
</div>
  </div>

<script>
    function expandCell(cell) {
        cell.classList.toggle("expanded");
    }
</script>

  {% endblock %}

web_ui/web_app/app/templates/page/turbo_component/dataset_change.html
<div id="dataset_change" class=" dataset_change">

    <h2>Stato Dataset </h2>


{% if dataset_change %}
    <p>Modifiche al Dataset agggiorna la versione {{repo_name}}</p>
    <a class="btn btn-primary" href="/update_dataset_version/{{current_dataset_id}}" > Aggiorna Versione </a>
{% else %}
    <p>Nessuna modifica aggiornato all'ultima versione</p>
{% endif %}

</div>

web_ui/web_app/app/templates/page/turbo_component/epoch_counter.html
<div id="epoch_counter" class="epoch_counter">
  <table>
    <tr>
      <th></th>
      <th>1 min</th>
      <th>5 min</th>
      <th>15 min</th>
    </tr>
    <tr>
      <th>Load averages:</th>
      <td>{{ load1 }}</td>
      <td>{{ load5 }}</td>
      <td>{{ load15 }}</td>
    </tr>
  </table>
</div>

web_ui/web_app/app/templates/page/turbo_component/loss_chart.html
<div id="chart1">

 
</div>

<script type="text/javascript">
    var loss_train_graph = {{ loss_train | safe}};
    Plotly.plot("chart1", loss_train_graph, {});
</script>